# DO NOT EDIT THIS FILE!
#
# Python module KanamuraRobotics__POA generated by omniidl

import omniORB
omniORB.updateModule("KanamuraRobotics__POA")

# ** 1. Stub files contributing to this module
import VelocitySwitcher_idl

# ** 2. Sub-modules

# ** 3. End
